version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  mysql:
    restart: always
    image: mysql
    command: --dashboard-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      # Пароль к БД
      MYSQL_ROOT_PASSWORD: Passw0rd_menly
      # Создаваемая по умолчанию бд
      MYSQL_DATABASE: menly_db